name: Terraform plan
on:
  pull_request_target:
    branches:
      - main

permissions:
  contents: read

jobs:
  plan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - id: plan
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: terraform plan -no-color 2>&1 | tee plan.txt
        continue-on-error: true

      - name: Add comment on PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr comment ${{ github.event.pull_request.number }} --body-file plan.txt
